inherit_from: configs/FastCaMo-large/FastCaMo-large.yaml

mapping:
  # Still have bound here, but have better meaning.
  bound: [[-3.5, 27.0], [-18.0, 4.0], [-5.0, 5.0]]
  marching_cubes_bound: [[-3.5, 27.0], [-18.0, 4.0], [-5.0, 5.0]]
  sample: 1800
  pixels_cur: 600
  localMLP_num: 20
  iters: 10
  keyframe_every: 15  # insert keyframe at constant speed
  min_containing_ratio: 0.75
  min_containing_ratio_mo: 0.8
  min_containing_ratio_back: 0.9
  map_every: 3
  pose_accum_step: 2

tracking:
  switch:
    min_correspondence: 15000

grid:
  hash_size: 16

data:
  datadir: /home/robotics/Disks/Data/OpenDataset/MIPS-Fusion/FastCaMo-large/floor1
  trainskip: 1
  output: /home/robotics/Disks/Data/OpenDataset/MIPS-Fusion/FastCaMo-large/floor1/output/FastCaMo-large/floor1_2
  exp_name: "0"
  starting_frame: -1